services:

  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application-example
    environment:
      DB_URL: jdbc:postgresql://database-example:5432/example
      DB_USER: abuser
      DB_PASSWORD: abuser
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
    ports:
      - "8081:8080"
    networks:
      - backend

  postgres:
    image: postgres:17
    container_name: database-example
    environment:
      POSTGRES_USER: abuser
      POSTGRES_PASSWORD: abuser
      POSTGRES_DB: example
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend: